spring:
  application:
    name: product-service
  profiles:
    active: local
  cloud:
    bootstrap:
      enabled: true
    config:
      discovery:
        enabled: true
        service-id: "config-server"
  config:
    import: "configserver:"


server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

message: "default message"